micronaut:
  application:
    name: kotlinMicronautCli
  http:
    client:
      logger-name: test
    services:
      shutdown-quiet-period: 0
  netty:
    event-loops:
      shutdown-quiet-period: 0
spotify:
  api:
    url: https://api.spotify.com
    oauth: ${SPOTIFY_OAUTH}
